Fix: Change Subscribe/Unsubscribe to use bidirectional channels
- Changed Subscribe() return type from '<-chan string' to 'chan string'
- Changed Unsubscribe() parameter from '<-chan string' to 'chan string'
- Removed type assertion that was causing compile error
- Now compiles successfully with 'make build'

This fixes the compilation error:
  'invalid operation: ch (variable of type <-chan string) is not an interface'

The bidirectional channel is needed because:
1. Map uses 'chan string' as key type
2. We need to close the channel on unsubscribe
3. Type assertions between channel directions don't work